language: go
go:
- 1.1
- 1.2
- 1.3

env:
  - KAFKA_INSTALL_ROOT=/home/travis/kafka KAFKA_HOSTNAME=localhost

before_install:
- export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}
- vagrant/install_cluster.sh
- vagrant/boot_cluster.sh
- vagrant/create_topics.sh
- go install -a -race regexp # Fix for go 1.2

script:
- go test -v -race ./...
- if [[ -n $(go fmt ./...) ]]; then echo "Please run go fmt on your code." && exit 1; fi

notifications:
  flowdock: 15e08f7ed3a8fd2d89ddb36435301c1a
